name: Build Github Page
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install
        run: npm install
      - name: Release Version
        run: |
          node bin/release-version.js
          git add src/version
          git commit -m "Released version $(cat src/version)"
          git push origin master
      - name: Build
        run: npm run build
      - name: Configure Git
        run: |
          git config --global user.name "Ethereal"
          git config --global user.email "ethereal97@gmail.com"
      - name: Github Page
        run: |
          mv dist docs
          rm -rf 
          git checkout --orphan gh-pages
          git add .
          git commit -m "Commited to Github Page"
          git push origin gh-pages --force
